--- #YAML:1.0
name:               App-psst
version:            0.04
abstract:           prompt string setting tool
author:
    - Matthew Astley <mca1001@users.sourceforge.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:   0
    Time::HiRes:  1.9713
requires:
    local::lib:   1.008
    perl:         5.006
    Test::More:   0
    Time::HiRes:  1.9713
resources:
    homepage:  https://github.com/mca-wtsi/psst
    Repository:
        type:  git
        url:   git@github.com:mca-wtsi/psst.git
        web:   https://github.com/mca-wtsi/psst
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    config:
        description:  Ability to read ~/.psst.yaml
        requires:
            YAML:  0.71
